"""Generate browser catalog from the canonical JSON (no network required).
After editing database/curriculum.json run this script.
"""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
data = json.loads((root / 'database/curriculum.json').read_text(encoding='utf-8'))
(root / 'assets/js/curriculum.js').write_text(
    '// Generated by scripts/build_curriculum.py; edit database/curriculum.json.\n'
    'window.TUTOR_CURRICULUM = ' + json.dumps(data, ensure_ascii=False, indent=2) + ';\n',
    encoding='utf-8')
(root / 'assets/js/problem_workshop_data.js').write_text(
    '// Generated from database/problem_workshop.json.\nwindow.PROBLEM_WORKSHOP = '+
    (root/'database/problem_workshop.json').read_text(encoding='utf8')+';\n',encoding='utf8')
