import json
from pathlib import Path
p=Path('database/curriculum.json'); d=json.loads(p.read_text(encoding='utf8'))
aliases={
'funciones:concepto':['funcion','funciones'], 'funciones:clasificacion':['inyectiva','sobreyectiva','biyectiva'],
'funciones:lineal':['funcion lineal'], 'funciones:constante':['funcion constante'], 'funciones:exponencial':['exponencial','exponenciales'], 'funciones:logaritmica':['logaritmo','logaritmos','logaritmica'], 'funciones:modulo':['valor absoluto','funcion modulo'], 'funciones:parte_entera':['parte entera'],
'trigonometria:seno':['seno','sen'], 'trigonometria:coseno':['coseno','cos'], 'trigonometria:tangente':['tangente','tan','tg'], 'trigonometria:reciprocas':['cosecante','secante','cotangente','reciprocas'], 'trigonometria:arcseno':['arcsen','arcseno','arcsin','seno inverso','inversa del seno','sen-1','sen⁻¹'], 'trigonometria:arccoseno':['arccos','arccoseno','coseno inverso','inversa del coseno','cos-1','cos⁻¹'], 'trigonometria:arctangente':['arctan','arctangente','tangente inversa','inversa de la tangente','tg-1','tg⁻¹','tan-1'], 'trigonometria:grados_radianes':['radian','radianes','grados'], 'trigonometria:triangulo':['triangulo rectangulo','hipotenusa','catetos'], 'trigonometria:circunferencia':['circunferencia','circulo unitario'], 'trigonometria:signos':['cuadrante','cuadrantes','signos'], 'trigonometria:identidades':['identidad trigonometrica','identidades'], 'trigonometria:amplitud':['amplitud'], 'trigonometria:periodo':['periodo','frecuencia'], 'trigonometria:notables':['angulos notables'],
'geometria:pendiente':['pendiente'], 'geometria:distancia':['distancia entre puntos','distancia entre dos puntos'], 'geometria:punto_medio':['punto medio'], 'geometria:paralelas':['paralelas'], 'geometria:perpendiculares':['perpendiculares'], 'geometria:ecuacion':['ecuacion de la recta'], 'geometria:distancia_recta':['distancia de un punto a una recta'],
'combinatoria:factorial':['factorial','factoriales'], 'combinatoria:conteo':['conteo','principio multiplicativo'], 'combinatoria:variacion':['variacion','variaciones','arreglos'], 'combinatoria:permutacion':['permutacion','permutaciones'], 'combinatoria:combinacion':['combinacion','combinaciones'], 'combinatoria:concepto':['combinatoria','analisis combinatorio']}
cards=[]
for u in d['units']:
 for t in u['subtopics']:
  section=t['sections'][0];key=u['key']+':'+t['id']
  cards.append({'key':key,'topic':u['key'],'subtopic':t['id'],'title':t['title'],'aliases':aliases.get(key,[t['title']]),'definition':section['concept'],'detail':section['alternative'],'example':section['example'],'example_alt':section['example_alt'],'formula':section['formula'],'visual':section['visual']})
for c in cards:
 if c['key']=='trigonometria:tangente':
  c.update(detail='Primero elegí un ángulo agudo en un triángulo rectángulo. El cateto opuesto está frente a ese ángulo y el adyacente está a su lado, sin ser la hipotenusa. La tangente compara cuánto se sube con cuánto se avanza horizontalmente. Si agrandás el triángulo conservando sus ángulos, ambos catetos cambian en la misma proporción: su cociente permanece igual. Por eso esta razón depende del ángulo, no del tamaño del triángulo.',why='El seno es el cateto opuesto dividido por la hipotenusa y el coseno es el adyacente dividido por la hipotenusa. Al dividir esas dos razones, la hipotenusa se cancela y queda opuesto dividido por adyacente. La condición cos(θ) ≠ 0 es necesaria porque dividir por cero no está definido. A 90° y 270° el coseno es cero: la tangente no existe allí; no es un valor infinito.',usage='Se usa para relacionar altura y distancia horizontal en rampas, pendientes y mediciones indirectas. Identificá primero cuál de esas longitudes conocés y cuál buscás. Si conocés una razón entre catetos y querés hallar el ángulo principal, usás arctan, no la tangente directa.',warning='No dividas por la hipotenusa: eso corresponde al seno o al coseno. La tangente es positiva en los cuadrantes I y III, negativa en II y IV, y se repite cada 180°. Su gráfica tiene asíntotas verticales y no tiene amplitud.',visual={'type':'function_graph','funcType':'tan'})
 if c['key']=='trigonometria:seno':c.update(detail='Elegí el ángulo de referencia: el cateto opuesto está frente a él y la hipotenusa frente al ángulo recto. El seno compara esas dos longitudes. En la circunferencia de radio uno, el seno representa la altura del punto; esta interpretación permite extenderlo a ángulos mayores que un ángulo recto.',why='La altura del punto es la proyección vertical del radio. Como el radio de la circunferencia unitaria mide uno, altura dividida por radio coincide con la coordenada vertical. El signo depende de si el punto está encima o debajo del eje horizontal.',warning='No confundas el cateto opuesto con el adyacente: sus nombres cambian si elegís otro ángulo. El seno siempre queda entre −1 y 1.',visual={'type':'function_graph','funcType':'sin'})
 if c['key']=='trigonometria:coseno':c.update(detail='El coseno compara el cateto adyacente al ángulo con la hipotenusa. En la circunferencia unitaria, corresponde a la coordenada horizontal del punto. Es positivo a la derecha del eje vertical y negativo a la izquierda.',why='El cateto adyacente es la proyección horizontal del radio. Al dividirlo por el radio unitario, obtenemos la coordenada horizontal. Esa es la razón por la que el coseno se asocia al eje horizontal.',warning='La hipotenusa es siempre el lado frente al ángulo recto. El coseno está entre −1 y 1; no confundas cos⁻¹ con el recíproco del coseno.',visual={'type':'function_graph','funcType':'cos'})
 if c['key']=='geometria:pendiente':c.update(detail='La pendiente mide el cambio vertical por cada unidad de cambio horizontal. Para dos puntos, restá sus coordenadas verticales y dividí por la diferencia de las horizontales, respetando el mismo orden. Una pendiente positiva describe una recta que sube hacia la derecha; una negativa, una recta que baja.',why='El cociente compara cambios, no posiciones absolutas. En una recta ese cociente se mantiene entre cualquier par de puntos distintos. Cuando no hay cambio horizontal, la recta es vertical y ese cociente no está definido.',warning='No confundas pendiente con ordenada al origen. La primera indica inclinación; la segunda, el cruce con el eje vertical.')
# Additional concepts often asked without the exact title of a lesson.
for key,title,alias,definition,detail in [
 ('dominio','Dominio',['dominio'],'El dominio es el conjunto de entradas para las que una función está definida.','Revisá las restricciones de la expresión antes de sustituir: un denominador no puede ser cero; una raíz de índice par necesita radicando no negativo en los reales; un logaritmo requiere argumento positivo. El contexto también puede restringir las entradas, por ejemplo a cantidades no negativas.'),
 ('recorrido','Recorrido o imagen',['recorrido','rango','imagen de una funcion'],'El recorrido reúne las salidas que la función realmente alcanza al usar las entradas de su dominio.','Dominio y recorrido responden a preguntas diferentes: qué valores pueden entrar y qué valores pueden salir. El codominio es el conjunto de llegada declarado; el recorrido puede ocupar solo una parte de él.')]:
 cards.append({'key':'funciones:'+key,'topic':'funciones','subtopic':'caracteristicas','title':title,'aliases':alias,'definition':definition,'detail':detail,'formula':'','visual':{'type':'none'},'example':'En f(x)=x² con dominio real, cualquier real puede entrar, pero las salidas son no negativas.','example_alt':'Una función constante toma distintas entradas y siempre devuelve la misma salida: su recorrido contiene un solo valor.'})
for c in cards:
 if c['key']=='trigonometria:tangente':
  c.update(domain='La tangente está definida para todos los ángulos excepto 90° + k·180°, con k entero. En radianes se excluyen π/2 + kπ. Allí el coseno vale cero y el cociente seno/coseno no se puede calcular.', signs='La tangente es positiva en I y III porque seno y coseno tienen el mismo signo; es negativa en II y IV porque sus signos son distintos. Sobre el eje horizontal vale cero; sobre el eje vertical no está definida.', graph='Su gráfica tiene ramas crecientes separadas por asíntotas verticales donde el coseno se anula. Cada rama cruza el eje horizontal y el patrón se repite cada π radianes. No unas los extremos de ramas diferentes ni interpretes las asíntotas como puntos de la función.')
 if c['key'] in ['trigonometria:seno','trigonometria:coseno']:
  sine=c['subtopic']=='seno'
  c.update(domain='Su dominio es todo R y su recorrido es [−1, 1]. Cualquier ángulo real puede entrar, pero la coordenada de un punto sobre la circunferencia unitaria no puede superar el radio en valor absoluto.',signs='El seno es positivo en I y II, negativo en III y IV; vale cero sobre el eje horizontal.' if sine else 'El coseno es positivo en I y IV, negativo en II y III; vale cero sobre el eje vertical.',graph='La gráfica es una onda de período 2π radianes, con valores entre −1 y 1. '+('Pasa por el origen y comienza subiendo.' if sine else 'En el origen alcanza su máximo.'))
d['question_comparisons']={
 'trigonometria:seno|trigonometria:coseno':'Ambas razones usan la hipotenusa como denominador. El seno usa el cateto opuesto y la coordenada vertical; el coseno usa el adyacente y la horizontal. El ángulo de referencia debe ser el mismo al compararlas.',
 'trigonometria:tangente|trigonometria:arctangente':'La tangente recibe un ángulo y devuelve una razón. Arctan recibe una razón y devuelve un ángulo principal entre −90° y 90°, sin incluir los extremos. Arctan no es el recíproco de la tangente.',
 'combinatoria:permutacion|combinatoria:combinacion':'En una permutación importa el orden; cambiar posiciones puede crear otra disposición. En una combinación se elige un grupo sin importar el orden: reordenar el mismo grupo no crea una selección nueva.',
 'funciones:dominio|funciones:recorrido':'El dominio describe las entradas admitidas; el recorrido describe las salidas alcanzadas. Para encontrarlos se revisan condiciones diferentes: restricciones de entrada y valores posibles de salida.'}
# Focused answers are separate from definitions: do not answer a range query with a domain.
focused = {
 'trigonometria:tangente': {
  'simple':'Imaginá una rampa. Para un mismo ángulo, la tangente compara lo que subís con lo que avanzás horizontalmente: altura dividida por avance. En el triángulo rectángulo, eso es cateto opuesto dividido por cateto adyacente.',
  'range':'El recorrido de la tangente es todo R: puede tomar cualquier valor real. Cada rama pasa por todos esos valores; las asíntotas no pertenecen a la gráfica.',
 },
 'trigonometria:seno': {'simple':'El seno compara el cateto opuesto al ángulo con la hipotenusa. En la circunferencia unitaria, pensalo como la altura del punto.','range':'El recorrido del seno es [−1, 1], incluidos ambos extremos. En la circunferencia unitaria, la altura nunca supera el radio en valor absoluto.'},
 'trigonometria:coseno': {'simple':'El coseno compara el cateto adyacente al ángulo con la hipotenusa. En la circunferencia unitaria, indica la posición horizontal del punto.','range':'El recorrido del coseno es [−1, 1], incluidos ambos extremos. La coordenada horizontal de la circunferencia unitaria queda entre esos valores.'},
 'trigonometria:arcseno': {'domain':'El dominio de arcsen es [−1, 1]. Su entrada es una razón, no un ángulo.','range':'El recorrido principal de arcsen es [−π/2, π/2], o [−90°, 90°], incluidos los extremos.'},
 'trigonometria:arccoseno': {'domain':'El dominio de arccos es [−1, 1]. Su entrada es una razón, no un ángulo.','range':'El recorrido principal de arccos es [0, π], o [0°, 180°], incluidos los extremos.'},
 'trigonometria:arctangente': {'domain':'El dominio de arctan es todo R: admite cualquier razón real como entrada.','range':'El recorrido principal de arctan es (−π/2, π/2), o (−90°, 90°), sin incluir los extremos.'},
 'funciones:lineal': {'domain':'Una función lineal f(x)=mx+b está definida para todo x real, salvo restricciones adicionales del contexto.','range':'Si la pendiente m no es cero, el recorrido de f(x)=mx+b es todo R. Si m=0, es constante y su recorrido es solo {b}.'},
 'funciones:constante': {'domain':'La expresión f(x)=k admite todo x real; el enunciado puede restringir ese dominio.','range':'El recorrido de una función constante f(x)=k es {k}: todas las entradas admitidas producen la misma salida.'},
 'funciones:exponencial': {'domain':'La función exponencial básica f(x)=a^x, con a>0 y a≠1, tiene dominio R.','range':'La exponencial básica f(x)=a^x tiene recorrido (0, +∞): siempre es positiva y nunca alcanza cero. Los desplazamientos o factores de otra expresión pueden cambiar ese recorrido.'},
 'funciones:logaritmica': {'domain':'En la función básica f(x)=log_a(x), con a>0 y a≠1, el dominio es (0, +∞). Si el argumento es otra expresión, esa expresión debe ser positiva.','range':'La función logarítmica básica tiene recorrido R: sus salidas pueden ser positivas, negativas o cero.'},
 'funciones:modulo': {'domain':'La función básica f(x)=|x| tiene dominio R.','range':'El recorrido de f(x)=|x| es [0, +∞): un valor absoluto nunca es negativo.'},
 'funciones:parte_entera': {'domain':'La función parte entera f(x)=⌊x⌋ tiene dominio R.','range':'El recorrido de la parte entera es Z, el conjunto de números enteros. Aunque la entrada sea decimal, la salida siempre es un entero.'},
 'geometria:pendiente': {'simple':'La pendiente compara cuánto sube o baja una recta con cuánto avanzás hacia la derecha. Si sube es positiva; si baja es negativa. Una recta vertical no tiene pendiente real definida.'},
}
for card in cards:
 card.update(focused.get(card['key'], {}))
 # Explicit, bounded spelling variants; never fuzzy-match arbitrary user words.
 if card['key']=='trigonometria:tangente':card['aliases']+=['tanjente','tangete']
 if card['key']=='trigonometria:coseno':card['aliases']+=['coseno trigonometrico']

d['question_bank']=cards
p.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf8')

# Reapply glossary and inverse-function content after rebuilding lesson cards.
import runpy
runpy.run_path(str(Path(__file__).resolve().with_name("build_glossary.py")))
