from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
data=json.loads((root/'database/language_profiles.json').read_text(encoding='utf8'))
(root/'assets/js/language_data.js').write_text('// Generated by scripts/build_languages.py. Edit database/language_profiles.json.\nwindow.TUTOR_LANGUAGE_DATA = '+json.dumps(data,ensure_ascii=False,indent=2)+';\n',encoding='utf8')
