const {chromium}=require('C:/Users/bogad/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
for(const width of [320,390,768,1365]){
 const page=await browser.newPage({viewport:{width,height:900}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:8127')?r.continue():r.abort());await page.addInitScript(()=>{localStorage.setItem('widget_formula','collapsed');localStorage.setItem('widget_visual','collapsed');});
 await page.goto('http://127.0.0.1:8127/index.php');assert.equal(await page.locator('[data-widget-id=progress],.widget-toggle-btn').count(),0);
 for(const id of ['formula','visual']){const card=page.locator(`[data-widget-id=${id}]`);await card.locator('.widget-header').click();assert.ok(await card.locator('.widget-body').isVisible());assert.equal(await card.locator('.widget-body').evaluate(el=>getComputedStyle(el).maxHeight),'none');}
 await page.locator('#btn-toggle-sidebar').click();await page.locator('.curriculum-unit').first().locator('summary').click();await page.getByRole('button',{name:'Función lineal',exact:true}).click();await page.locator('#chat-input').fill('que es seno');await page.locator('#send-btn').click();await page.waitForFunction(()=>!document.getElementById('typing-indicator'));
 assert.equal(await page.getByLabel('Función trigonométrica').inputValue(),'sin');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 const body=page.locator('[data-widget-id=visual] .widget-body');assert.ok(await body.evaluate(el=>el.scrollHeight<=el.clientHeight+1),'visual content must not be clipped');
 if(width<=960){assert.ok(await page.locator('.mobile-study-nav').isVisible());assert.ok(await page.locator('#chat-input').evaluate(el=>parseFloat(getComputedStyle(el).fontSize)>=16));await page.locator('.mobile-study-nav a').first().click();await page.screenshot({path:`tmp/pdfs/mobile-chat-${width}.png`});await page.locator('.mobile-study-nav a').last().click();await page.screenshot({path:`tmp/pdfs/mobile-graph-${width}.png`});}
 assert.ok(!requests.some(url=>url.includes('api/progress.php')));assert.deepEqual(errors,[]);await page.close();
}await browser.close();console.log('PASS: permanent panels, no progress fetch/panel, unclipped graphs, chat interaction and 320/390/768/1365px layouts');})().catch(e=>{console.error(e);process.exit(1)});
