const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');global.window={};for(const f of ['curriculum','language_data','language','problem_guide','question_resolver','problem_workshop_data','natural_problem','workshop_expression','general_problem','problem_workshop','trig_questions','lesson_engine'])vm.runInThisContext(fs.readFileSync(`assets/js/${f}.js`,'utf8'));
const problem='Un árbol proyecta una sombra de 6 metros. Si el ángulo de elevación del Sol es de 30°, ¿cuánto mide el árbol?';
const events=[[problem,''],['siguiente','next_step'],['siguiente','next_step'],['6 m',''],['3,46 metros',''],['otro','new_problem'],['Un árbol proyecta una sombra de seis metros. ¿Cuánto mide el árbol?',''],['El ángulo de elevación es de treinta grados.',''],['346 cm','']];let state=LessonEngine.initial('funciones','concepto');state.workshop={stage:'statement'};const actual=events.map(([m,a])=>{if(state.workshop.stage==='topic'&&a!=='new_problem')state=LessonEngine.transition(state,'No sé el tema','topic_unsure');state=LessonEngine.transition(state,m,a);if(state.workshop.stage==='confirm')state=LessonEngine.transition(state,'Sí, son correctos','confirm_data');return {workshop:state.workshop,response:LessonEngine.response(state)};});const php=spawnSync('C:/xampp1/php/php.exe',['tests/workshop_trace.php'],{input:JSON.stringify(events),encoding:'utf8'});assert.equal(php.status,0,php.stderr);assert.deepEqual(actual,JSON.parse(php.stdout));
assert.equal(actual[0].workshop.rule,'shadow_height');assert.match(actual[0].response.tutor_message_jopara,/6 m/);assert.match(actual[0].response.tutor_message_jopara,/30°/);assert.match(actual[1].response.tutor_message_jopara,/tangente/);assert.match(actual[2].response.tutor_message_jopara,/h = 6 · tan\(30°\)/);for(const item of actual.slice(0,4))assert.doesNotMatch(item.response.tutor_message_jopara,/3[.,]46|2√3/);assert.equal(actual[3].workshop.feedback,'incorrect');assert.equal(actual[4].workshop.stage,'correct');assert.equal(actual[7].workshop.rule,'shadow_height');assert.equal(actual[8].workshop.stage,'correct');
for(const [text,rule,value] of [
 ['El Sol tiene una elevación de 45 grados. Un poste proyecta 10 m de sombra. ¿Cuál es su altura?','shadow_height',10],
 ['Una escalera de 5 metros forma 30° con el suelo. ¿A qué altura llega?','ladder_height',2.5],
 ['Desde una distancia de 12 metros se ve una torre con ángulo de elevación de 45°. ¿Cuál es su altura?','elevation_height',12],
 ['Una torre tiene 20 metros de altura. Su ángulo de elevación es 45°. ¿Cuál es la distancia a su base?','elevation_distance',20]
]){const plan=ProblemWorkshop.parse(text);assert.equal(plan.rule,rule);assert.ok(Math.abs(plan.expected-value)<1e-8);}
for(const text of [problem.replace('30°','90°'),problem.replace('6 metros','-6 metros'),problem+' El suelo es inclinado.',problem.replace('6 metros','6 metros y 8 metros'),problem.replace('30°','0.5 radianes')])assert.equal(ProblemWorkshop.parse(text),null);
console.log('PASS: actual tree statement, four natural-language families, word numbers, reordered data, missing-data follow-up, units, rounding, no premature result, PHP/JS parity and ambiguous cases');
