const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
global.window={};for(const f of ['curriculum','language_data','language','problem_guide','question_resolver','trig_questions','lesson_engine'])vm.runInThisContext(fs.readFileSync(`assets/js/${f}.js`,'utf8'));
const events=[['que es un triangulo rectangulo',''],['dame un ejemplo','example'],['que es semejanza de triangulos',''],['que son razones trigonometricas','']];
let state=LessonEngine.initial('funciones','trigonometricas_intro');const results=events.map(([m,a])=>{state=LessonEngine.transition(state,m,a);return {state,response:LessonEngine.response(state)};});
const php=spawnSync('C:/xampp1/php/php.exe',['tests/question_trace.php'],{input:JSON.stringify(events),encoding:'utf8'});assert.equal(php.status,0,php.stderr);const expected=JSON.parse(php.stdout);for(let i=0;i<results.length;i++){delete expected[i].response.pedagogical_state;assert.deepEqual(results[i],expected[i]);}
assert.match(results[0].response.tutor_message_jopara,/90°/);assert.match(results[0].response.tutor_message_jopara,/catetos/);assert.match(results[0].response.tutor_message_jopara,/hipotenusa/);assert.doesNotMatch(results[0].response.tutor_message_jopara,/semejantes|proporcionales/);assert.equal(results[0].response.visual_action.triangle_mode,'single');assert.equal(results[0].response.formula_display.latex,'a^2+b^2=h^2');
assert.match(results[1].response.tutor_message_jopara,/3 cm y 4 cm/);assert.match(results[2].response.tutor_message_jopara,/proporcionales/);assert.match(results[3].response.tutor_message_jopara,/seno=opuesto/);
const lesson=window.TUTOR_CURRICULUM.units.find(u=>u.key==='trigonometria').subtopics.find(t=>t.id==='triangulo');assert.match(lesson.sections[0].concept,/tiene un ángulo recto/);assert.match(lesson.sections[1].concept,/semejantes/);
console.log('PASS: right-triangle definition, elements and example separated from similarity and ratios; PHP/JS parity');
