// Circle, angle, numerical table and curve share the same model.
class TopicTrigGraph extends TrigGraph {
 constructor(id,options={}) {
  super(id,options);this.angle=30;this.scale=1;
  for(const [v,n] of [['cot','Cotangente'],['sec','Secante'],['csc','Cosecante'],['triangle','Triángulos semejantes']])this.select.add(new Option(n,v));
  const label=document.createElement('label');label.textContent='Ángulo θ ';this.angleSlider=document.createElement('input');Object.assign(this.angleSlider,{type:'range',min:0,max:360,step:1,value:30});this.angleSlider.setAttribute('aria-label','Ángulo del gráfico');label.append(this.angleSlider);this.select.parentElement.parentElement.append(label);
  const sizeLabel=document.createElement('label');sizeLabel.textContent='Tamaño del triángulo ';this.scaleSlider=document.createElement('input');Object.assign(this.scaleSlider,{type:'range',min:0.5,max:2,step:0.1,value:1});this.scaleSlider.setAttribute('aria-label','Tamaño del triángulo');sizeLabel.append(this.scaleSlider);label.after(sizeLabel);
  this.angleSlider.oninput=()=>this.setParameters({angle:Number(this.angleSlider.value)});this.scaleSlider.oninput=()=>this.setParameters({scale:Number(this.scaleSlider.value)});
  this.select.onchange=()=>this.setParameters({funcType:this.select.value,amplitude:1,frequency:1,phaseShift:0,verticalShift:0});
  this.info=document.createElement('p');this.caption.after(this.info);this.table=document.createElement('div');this.table.className='trig-value-table';this.info.after(this.table);this.reference=document.createElement('details');this.reference.className='plot-reference';this.table.after(this.reference);
  this.canvas.style.touchAction='none';this.canvas.setAttribute('aria-label','Arrastrá el radio para cambiar el ángulo. También podés usar el control Ángulo del gráfico.');
  const position=e=>{const r=this.canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*this.canvas.width/r.width,y:(e.clientY-r.top)*this.canvas.height/r.height};};
  const move=e=>{if(!this.dragging)return;const p=position(e);let a=Math.atan2(this.circle.y-p.y,p.x-this.circle.x)*180/Math.PI;if(a<0)a+=360;this.setParameters({angle:Math.round(a)});};
  this.canvas.addEventListener('pointerdown',e=>{if(this.inverse||!this.circle)return;const p=position(e);if(Math.hypot(p.x-this.circle.x,p.y-this.circle.y)>this.circle.r+20)return;this.dragging=true;this.canvas.setPointerCapture(e.pointerId);move(e);});this.canvas.addEventListener('pointermove',move);for(const ev of ['pointerup','pointercancel','lostpointercapture'])this.canvas.addEventListener(ev,()=>this.dragging=false);this.draw();
 }
 setParameters(p){Object.assign(this,p);if(this.funcType==='triangle')this.angle=Math.max(5,Math.min(85,this.angle||30));this.draw();}
 static base(k,x){const s=Math.sin(x),c=Math.cos(x);if(['tan','sec'].includes(k)&&Math.abs(c)<1e-10||['cot','csc'].includes(k)&&Math.abs(s)<1e-10)return NaN;return k==='cot'?c/s:k==='sec'?1/c:k==='csc'?1/s:Math[k](x);}
 evaluate(x){return this.amplitude*TopicTrigGraph.base(this.funcType,this.frequency*x+this.phaseShift)+this.verticalShift;}
 branch(x){const t=this.frequency*x+this.phaseShift;return ['tan','sec'].includes(this.funcType)?Math.floor((t+Math.PI/2)/Math.PI):['cot','csc'].includes(this.funcType)?Math.floor(t/Math.PI):0;}
 fmt(v){return Number.isFinite(v)?String(Math.abs(v)<1e-9?0:Math.round(v*1000)/1000):'No definida';}
 draw(){
  if(!this.angleSlider)return;
  const triangle=this.funcType==='triangle',inverse=this.inverse=['asin','acos','atan'].includes(this.funcType);
  this.select.querySelector('option[value="triangle"]').textContent=this.triangleMode==='single'?'Triángulo rectángulo':'Triángulos semejantes';
  this.angleSlider.parentElement.hidden=inverse;this.scaleSlider.parentElement.hidden=!triangle;this.slider.parentElement.hidden=triangle;
  this.angleSlider.min=triangle?5:0;this.angleSlider.max=triangle?85:360;this.angleSlider.value=this.angle;this.scaleSlider.value=this.scale;
  if(inverse){super.draw();this.info.textContent='La inversa devuelve un ángulo principal. No es la función recíproca.';this.table.replaceChildren();this.reference.hidden=true;return;}
  const parentStyle=getComputedStyle(this.canvas.parentElement);
  const w=this.canvas.width=Math.max(220,(this.canvas.parentElement.clientWidth||340)-parseFloat(parentStyle.paddingLeft||0)-parseFloat(parentStyle.paddingRight||0)),h=this.canvas.height=430,ctx=this.ctx;ctx.clearRect(0,0,w,h);ctx.font='12px sans-serif';ctx.lineWidth=1;ctx.textAlign='left';
  const line=(x,y,a,b,c='#48665b')=>{ctx.strokeStyle=c;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(a,b);ctx.stroke();};
  const dot=(x,y)=>{ctx.fillStyle='#e37519';ctx.beginPath();ctx.arc(x,y,5,0,2*Math.PI);ctx.fill();};
  const theta=this.angle*Math.PI/180,cx=w/2,cy=83,r=60;this.circle={x:cx,y:cy,r};ctx.strokeStyle='#688b7d';ctx.beginPath();ctx.arc(cx,cy,r,0,2*Math.PI);ctx.stroke();line(cx-r-8,cy,cx+r+8,cy);line(cx,cy-r-8,cx,cy+r+8);
  const x=cx+r*Math.cos(theta),y=cy-r*Math.sin(theta);line(cx,cy,x,y,'#db7d16');line(x,cy,x,y,'#db3890');line(cx,cy,x,cy,'#0495a8');dot(x,y);ctx.fillStyle='#174c42';ctx.fillText(`θ = ${this.angle}° = ${this.fmt(theta)} rad`,8,17);ctx.fillText(`x = ${this.fmt(Math.cos(theta))}   y = ${this.fmt(Math.sin(theta))}`,8,163);
  if(triangle){
   const single=this.triangleMode==='single',ox=32,oy=390,radius=Math.min(w-65,180);for(const [len,color] of (single?[[radius*this.scale/2,'#009baf']]:[[radius,'#a1beb2'],[radius*this.scale/2,'#009baf']])){const x=ox+len*Math.cos(theta),y=oy-len*Math.sin(theta);line(ox,oy,x,oy,color);line(x,oy,x,y,color);line(x,y,ox,oy,color);if(single){const mark=Math.min(10,(oy-y)/3,(x-ox)/3);line(x-mark,oy,x-mark,oy-mark);line(x-mark,oy-mark,x,oy-mark);ctx.fillStyle='#174c42';ctx.fillText('90°',x+5,oy-4);ctx.fillText('cateto',(ox+x)/2-20,oy+18);ctx.fillText('cateto',x+5,(y+oy)/2);ctx.fillText('hipotenusa',Math.max(8,(ox+x)/2-40),(y+oy)/2-12);}}
   ctx.fillStyle='#174c42';ctx.fillText(single?'Triángulo rectángulo y sus lados':'Mismo ángulo → mismas razones',12,196);const hyp=30*this.scale,op=hyp*Math.sin(theta),adj=hyp*Math.cos(theta);
   this.caption.textContent=`θ = ${this.angle}° · hipotenusa = ${this.fmt(hyp)} · opuesto = ${this.fmt(op)} · adyacente = ${this.fmt(adj)}\nsen θ = ${this.fmt(op)}/${this.fmt(hyp)} ≈ ${this.fmt(Math.sin(theta))} · cos θ ≈ ${this.fmt(Math.cos(theta))} · tan θ ≈ ${this.fmt(Math.tan(theta))}`;
   if(single)this.caption.textContent=`Catetos: ${this.fmt(op)} y ${this.fmt(adj)} · Hipotenusa: ${this.fmt(hyp)}\na² + b² = h² → ${this.fmt(op*op)} + ${this.fmt(adj*adj)} = ${this.fmt(hyp*hyp)} (valores aproximados)`;
   this.info.textContent=single?'El cuadradito marca 90°. Los catetos forman ese ángulo; la hipotenusa está enfrente. Al mover el ángulo agudo, el triángulo sigue teniendo un ángulo recto.':'Cambiá el tamaño: los lados varían proporcionalmente y las razones se conservan. Cambiá el ángulo: las razones cambian. Opuesto y adyacente dependen del ángulo elegido.';this.table.replaceChildren();
  }else{
   const left=35,right=w-14,top=194,bottom=h-38,ymax=Math.max(2,Math.abs(this.amplitude)+Math.abs(this.verticalShift)+0.4,['tan','cot','sec','csc'].includes(this.funcType)?4:0),px=x=>left+x/(2*Math.PI)*(right-left),py=y=>bottom-(y+ymax)/(2*ymax)*(bottom-top);
   ctx.fillStyle='#174c42';ctx.textAlign='center';for(let i=0;i<5;i++){const x=i*Math.PI/2;line(px(x),top,px(x),bottom,'#dce8e1');ctx.fillText(['0','π/2','π','3π/2','2π'][i],px(x),bottom+15);ctx.fillText(`${i*90}°`,px(x),bottom+30);}ctx.textAlign='left';for(let y=-Math.floor(ymax);y<=ymax;y++)if(y)ctx.fillText(String(y),2,py(y)+4);line(left,py(0),right,py(0));line(left,top,left,bottom);
   ctx.save();ctx.beginPath();ctx.rect(left,top,right-left,bottom-top);ctx.clip();
   if(['tan','cot','sec','csc'].includes(this.funcType)&&this.frequency!==0){ctx.setLineDash([4,4]);const offset=['tan','sec'].includes(this.funcType)?Math.PI/2:0,lo=Math.min(this.phaseShift,2*Math.PI*this.frequency+this.phaseShift),hi=Math.max(this.phaseShift,2*Math.PI*this.frequency+this.phaseShift);for(let k=Math.ceil((lo-offset)/Math.PI);k<=(hi-offset)/Math.PI;k++){const x=(offset+k*Math.PI-this.phaseShift)/this.frequency;line(px(x),top,px(x),bottom,'#b67968');}ctx.setLineDash([]);}
   ctx.strokeStyle='#d93289';ctx.lineWidth=2.3;ctx.beginPath();let previous=null,branch=null;for(let p=left;p<=right;p+=0.5){const x=(p-left)/(right-left)*2*Math.PI,y=this.evaluate(x),b=this.branch(x);if(!Number.isFinite(y)||Math.abs(y)>ymax*3){previous=null;continue;}if(previous===null||branch!==b)ctx.moveTo(p,py(y));else ctx.lineTo(p,py(y));previous=y;branch=b;}ctx.stroke();const selected=this.evaluate(theta);line(px(theta),top,px(theta),bottom,'#e6af52');if(Number.isFinite(selected))dot(px(theta),py(selected));ctx.restore();
   this.caption.textContent=`y = ${this.amplitude} · ${this.funcType==='sin'?'sen':this.funcType}(${this.frequency}θ ${this.phaseShift<0?'−':'+'} ${Math.abs(this.phaseShift)}) ${this.verticalShift<0?'−':'+'} ${Math.abs(this.verticalShift)}\nθ = ${this.angle}° → y = ${this.fmt(selected)}`;
   const notes={sin:'Altura en la circunferencia. Crece en I y IV; decrece en II y III.',cos:'Coordenada horizontal. Decrece en I y II; crece en III y IV.',tan:'sen θ / cos θ. No definida en 90° y 270°; ramas crecientes.',cot:'cos θ / sen θ. No definida en 0°, 180° y 360°; ramas decrecientes.',sec:'1 / cos θ. No definida en 90° y 270°. No toma valores entre −1 y 1.',csc:'1 / sen θ. No definida en 0°, 180° y 360°. No toma valores entre −1 y 1.'};
   this.info.textContent=`Función base: ${notes[this.funcType]} Período: ${['tan','cot'].includes(this.funcType)?'π (180°)':'2π (360°)'}. La curva y tabla reflejan las transformaciones seleccionadas. Las asíntotas no son valores infinitos de la función.`;
   const table=document.createElement('table');table.innerHTML='<caption>Valores aproximados de la curva seleccionada</caption><thead><tr><th>θ</th><th>Radianes</th><th>y</th></tr></thead>';const body=document.createElement('tbody');for(const a of [0,30,45,60,90,120,150,180,210,240,270,300,330,360]){const row=body.insertRow();for(const t of [`${a}°`,this.fmt(a*Math.PI/180),this.fmt(this.evaluate(a*Math.PI/180))])row.insertCell().textContent=t;}table.append(body);this.table.replaceChildren(table);
  }
  this.select.value=this.funcType;this.slider.value=this.amplitude;
  const reference={triangle:['trig-triangulos.png',24],sin:['trig-seno.png',28],cos:['trig-cos-tan.png',29],tan:['trig-cos-tan.png',29],cot:['trig-cot-sec.png',30],sec:['trig-cot-sec.png',30],csc:['trig-csc.png',31]}[this.funcType];this.reference.hidden=!reference;
  if(reference&&this.reference.dataset.kind!==this.funcType){this.reference.dataset.kind=this.funcType;const summary=document.createElement('summary');summary.textContent=`Ver figura del libro · página ${reference[1]}`;const img=document.createElement('img');img.src=`assets/books/figures/${reference[0]}`;img.alt=`Página ${reference[1]}: figura de ${this.select.selectedOptions[0].text}`;img.style.width='100%';img.loading='lazy';const a=document.createElement('a');a.href=`assets/books/matematica-1-mec-2016.pdf#page=${reference[1]+2}`;a.target='_blank';a.rel='noopener';a.textContent='Abrir página en el PDF';this.reference.replaceChildren(summary,img,a);}
 }
}
